#!/usr/bin/env bash
cd "$(dirname "$0")/../"
set -e
Rscript src/create_map.R "$@"
FILE=$([[ $1 == "--interactive" ]] && realpath "map.html" || realpath "map.png")
case "$OSTYPE" in
    darwin*)  open $FILE;; 
    linux*)   xdg-open $FILE;;
    msys*)    explorer $FILE;;
    cygwin*)  explorer $FILE;;
esac